[package]
name = "sval-generic-api-js"
version = "0.0.0"
edition = "2021"

[dependencies.sval-generic-api]
path = "../"

[dependencies.sval-generic-api-buffer]
path = "../buffer"

[dependencies.js-sys]
version = "0.3"

[dependencies.wasm-bindgen]
version = "0.2"
