[package]
name = "sval-generic-api"
version = "0.0.0"
edition = "2018"

[workspace]
members = [
    "coroutine",
    "derive",
    "json",
    "fmt",
    "serde",
    "valuable",
    "erased",
    "buffer",
    "json/benches/twitter",
    "json/benches/profile",
    "json/tests/twitter"
]

[dependencies.derive]
package = "sval-generic-api-derive"
path = "derive"
optional = true

[profile.release]
debug = true
opt-level = 3
lto = "fat"
codegen-units = 1
