[package]
name = "sval"
version = "0.0.0"
edition = "2021"

[workspace]
members = [
    "derive",
    "derive/tests",
    "test",
    "json",
    "dynamic",
    "json/benches/twitter",
    "json/benches/profile",
    "json/tests",
    "json/tests/twitter",
]

[features]
std = ["alloc"]
alloc = []

[profile.release]
debug = true
opt-level = 3
lto = "fat"
codegen-units = 1
