[package]
name = "sval-generic-api"
version = "0.0.0"
edition = "2018"

[workspace]
members = [
    "derive",
    "json",
    "json/benches/twitter",
    "json/benches/profile",
    "json/tests/twitter"
]

[dependencies.serde]
version = "1"

[dependencies.valuable]
git = "https://github.com/tokio-rs/valuable"
branch = "taiki-e/json"

[dependencies.sval-generic-api-derive]
path = "derive"

[dependencies.async-trait]
version = "0.1"

[profile.release]
debug = true
opt-level = 3
lto = "fat"
codegen-units = 1
