[package]
name = "sval-generic-api"
version = "0.0.0"
edition = "2018"

[workspace]
members = [
    "derive",
    "json",
    "fmt",
    "serde",
    "valuable",
    "erased",
    "buffer",
    "json/benches/twitter",
    "json/benches/profile",
    "json/tests/twitter"
]

[dependencies.sval-generic-api-derive]
path = "derive"

[dependencies.async-trait]
version = "0.1"

[profile.release]
debug = true
opt-level = 3
lto = "fat"
codegen-units = 1
