[package]
name = "sval-generic-api-derive"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies.syn]
version = "1"

[dependencies.quote]
version = "1"

[dependencies.proc-macro2]
version = "1"
