[package]
name = "sval-buffer"
version = "0.0.0"
edition = "2021"

[features]
std = ["alloc"]
alloc = ["sval/alloc"]

[dependencies.sval]
path = "../"

[dev-dependencies.sval-derive]
path = "../derive"
