[package]
name = "sval-buffer"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2021"
publish = false

[dependencies.sval]
path = "../"

[dependencies.sval-fmt]
path = "../fmt"
