[package]
name = "sval-generic-api-buffer"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2018"
publish = false

[dependencies.sval-generic-api]
path = "../"

[dependencies.sval-generic-api-fmt]
path = "../fmt"
