[package]
name = "sval-example-browser"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies.sval]
path = "../../"

[dependencies.sval-js]
path = "../../js"

[dependencies.wasm-bindgen]
version = "0.2"
