[package]
name = "sval-json-twitter-profile"
version = "0.0.0"
publish = false
edition = "2021"

[[bin]]
name = "profile"
path = "main.rs"

[dependencies.sval-json]
path = "../../"

[dependencies.sval-json-twitter-tests]
path = "../../tests/twitter"

[dependencies.serde_json]
version = "1"
