[package]
name = "sval-json"
version = "0.0.0"
edition = "2021"

[dependencies.sval]
path = "../"

[dependencies.ryu]
version = "1"

[dependencies.itoa]
version = "0.4"
features = ["i128"]
default-features = false
