[package]
name = "sval-generic-api-json"
version = "0.0.0"
edition = "2018"

[dependencies.sval-generic-api]
path = "../"

[dependencies.ryu]
version = "1"

[dependencies.itoa]
version = "0.4"
features = ["i128"]
default-features = false
