[package]
name = "sval-fmt"
version = "0.0.0"
edition = "2021"

[features]
std = ["alloc"]
alloc = ["sval/alloc"]

[dependencies.sval]
path = "../"

[dependencies.ryu]
version = "1"

[dependencies.itoa]
version = "0.4"
features = ["i128"]
default-features = false
