[package]
name = "sval-serde"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2021"
publish = false

[dependencies.sval]
path = "../"

[dependencies.sval-buffer]
path = "../buffer"

[dependencies.serde]
version = "1"
