[package]
name = "sval-serde"
version = "0.0.0"
edition = "2021"

[features]
alloc = ["serde/alloc", "sval/alloc", "sval-buffer/alloc"]

[dependencies.sval]
path = "../"

[dependencies.sval-buffer]
path = "../buffer"

[dependencies.serde]
version = "1"
default-features = false
